# Generated by Django 5.0.3 on 2024-05-15 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partystats',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.party'),
        ),
        migrations.AddField(
            model_name='partystats',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.party'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tour_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tour_users',
            field=models.ManyToManyField(related_name='participated_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinlobby',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lobby'),
        ),
        migrations.AddField(
            model_name='userinlobby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lobby',
            name='users',
            field=models.ManyToManyField(through='game.UserInLobby', to=settings.AUTH_USER_MODEL),
        ),
    ]
