# Generated by Django 3.2.5 on 2023-12-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
