# Generated by Django 5.0.3 on 2024-05-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField()),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('point_to_win', models.IntegerField(default=5)),
                ('nb_parties_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DateTimeField()),
                ('date', models.DateField(auto_now=True)),
                ('winner', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PartyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_set', models.IntegerField(default=0)),
                ('lost_set', models.IntegerField(default=0)),
                ('ratio', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stat_User_by_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(unique=True)),
                ('tour_game', models.CharField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('nb_rounds', models.IntegerField(default=5)),
                ('current_round', models.IntegerField()),
                ('nb_players', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
